function tau_b = ForceTransformation(u)
u_T1=u(1);
u_T2=u(2);
u_T3=u(3);
u_T4=u(4);
u_T5=u(5);
u_T6=u(6);
global veh;
F_T1=u_T1*veh.d_T1;
m_T1=veh.b_T1*0.5*u_T1*veh.d_T1+vp(veh.r_T1,u_T1*veh.d_T1);
%% Thruster 2 force and moment calculation
F_T2=u_T2*veh.d_T2;
m_T2=veh.b_T2*0.5*u_T2*veh.d_T2+vp(veh.r_T2,u_T2*veh.d_T2);
%% Thruster 3 force and moment calculation
F_T3=u_T3*veh.d_T3;
m_T3=veh.b_T3*0.5*u_T3*veh.d_T3+vp(veh.r_T3,u_T3*veh.d_T3);
%% Thruster 4 force and moment calculation
F_T4=u_T4*veh.d_T4;
m_T4=veh.b_T4*0.5*u_T4*veh.d_T4+vp(veh.r_T4,u_T4*veh.d_T4);  
% Thruster 5 force and moment calculation
F_T5=u_T5*veh.d_T5;
m_T5=veh.b_T5*0.5*u_T5*veh.d_T5+vp(veh.r_T5,u_T5*veh.d_T5);  
% Thruster 6 force and moment calculation
F_T6=u_T6*veh.d_T6;
m_T6=veh.b_T6*0.5*u_T6*veh.d_T6+vp(veh.r_T6,u_T6*veh.d_T6);  
% total forces and moments generated by thrusters
tau_b=[F_T1;m_T1]+[F_T2;m_T2]+[F_T3;m_T3]+[F_T4;m_T4]+[F_T5;m_T5]+[F_T6;m_T6]; 